# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.product import Product
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GetProductResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, data: Product=None):
        """
        GetProductResponse - a model defined in Swagger

        :param message: The message of this GetProductResponse.
        :type message: str
        :param data: The data of this GetProductResponse.
        :type data: Product
        """
        self.swagger_types = {
            'message': str,
            'data': Product
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetProductResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetProductResponse of this GetProductResponse.
        :rtype: GetProductResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this GetProductResponse.

        :return: The message of this GetProductResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this GetProductResponse.

        :param message: The message of this GetProductResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> Product:
        """
        Gets the data of this GetProductResponse.

        :return: The data of this GetProductResponse.
        :rtype: Product
        """
        return self._data

    @data.setter
    def data(self, data: Product):
        """
        Sets the data of this GetProductResponse.

        :param data: The data of this GetProductResponse.
        :type data: Product
        """

        self._data = data

