# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.get_objects_by_image_id_response_data import GetObjectsByImageIdResponseData
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GetObjectsByImageIdResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, data: GetObjectsByImageIdResponseData=None):
        """
        GetObjectsByImageIdResponse - a model defined in Swagger

        :param message: The message of this GetObjectsByImageIdResponse.
        :type message: str
        :param data: The data of this GetObjectsByImageIdResponse.
        :type data: GetObjectsByImageIdResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': GetObjectsByImageIdResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetObjectsByImageIdResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetObjectsByImageIdResponse of this GetObjectsByImageIdResponse.
        :rtype: GetObjectsByImageIdResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this GetObjectsByImageIdResponse.

        :return: The message of this GetObjectsByImageIdResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this GetObjectsByImageIdResponse.

        :param message: The message of this GetObjectsByImageIdResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> GetObjectsByImageIdResponseData:
        """
        Gets the data of this GetObjectsByImageIdResponse.

        :return: The data of this GetObjectsByImageIdResponse.
        :rtype: GetObjectsByImageIdResponseData
        """
        return self._data

    @data.setter
    def data(self, data: GetObjectsByImageIdResponseData):
        """
        Sets the data of this GetObjectsByImageIdResponse.

        :param data: The data of this GetObjectsByImageIdResponse.
        :type data: GetObjectsByImageIdResponseData
        """

        self._data = data

