# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.box_object import BoxObject
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GetObjectsByImageIdResponseData(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, boxes: List[BoxObject]=None, image_id: str=None):
        """
        GetObjectsByImageIdResponseData - a model defined in Swagger

        :param boxes: The boxes of this GetObjectsByImageIdResponseData.
        :type boxes: List[BoxObject]
        :param image_id: The image_id of this GetObjectsByImageIdResponseData.
        :type image_id: str
        """
        self.swagger_types = {
            'boxes': List[BoxObject],
            'image_id': str
        }

        self.attribute_map = {
            'boxes': 'boxes',
            'image_id': 'image_id'
        }

        self._boxes = boxes
        self._image_id = image_id

    @classmethod
    def from_dict(cls, dikt) -> 'GetObjectsByImageIdResponseData':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetObjectsByImageIdResponse_data of this GetObjectsByImageIdResponseData.
        :rtype: GetObjectsByImageIdResponseData
        """
        return deserialize_model(dikt, cls)

    @property
    def boxes(self) -> List[BoxObject]:
        """
        Gets the boxes of this GetObjectsByImageIdResponseData.

        :return: The boxes of this GetObjectsByImageIdResponseData.
        :rtype: List[BoxObject]
        """
        return self._boxes

    @boxes.setter
    def boxes(self, boxes: List[BoxObject]):
        """
        Sets the boxes of this GetObjectsByImageIdResponseData.

        :param boxes: The boxes of this GetObjectsByImageIdResponseData.
        :type boxes: List[BoxObject]
        """

        self._boxes = boxes

    @property
    def image_id(self) -> str:
        """
        Gets the image_id of this GetObjectsByImageIdResponseData.

        :return: The image_id of this GetObjectsByImageIdResponseData.
        :rtype: str
        """
        return self._image_id

    @image_id.setter
    def image_id(self, image_id: str):
        """
        Sets the image_id of this GetObjectsByImageIdResponseData.

        :param image_id: The image_id of this GetObjectsByImageIdResponseData.
        :type image_id: str
        """

        self._image_id = image_id

