# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.get_images_by_keyword_response_data import GetImagesByKeywordResponseData
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GetImagesByKeywordResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, data: GetImagesByKeywordResponseData=None):
        """
        GetImagesByKeywordResponse - a model defined in Swagger

        :param message: The message of this GetImagesByKeywordResponse.
        :type message: str
        :param data: The data of this GetImagesByKeywordResponse.
        :type data: GetImagesByKeywordResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': GetImagesByKeywordResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetImagesByKeywordResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetImagesByKeywordResponse of this GetImagesByKeywordResponse.
        :rtype: GetImagesByKeywordResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this GetImagesByKeywordResponse.

        :return: The message of this GetImagesByKeywordResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this GetImagesByKeywordResponse.

        :param message: The message of this GetImagesByKeywordResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> GetImagesByKeywordResponseData:
        """
        Gets the data of this GetImagesByKeywordResponse.

        :return: The data of this GetImagesByKeywordResponse.
        :rtype: GetImagesByKeywordResponseData
        """
        return self._data

    @data.setter
    def data(self, data: GetImagesByKeywordResponseData):
        """
        Sets the data of this GetImagesByKeywordResponse.

        :param data: The data of this GetImagesByKeywordResponse.
        :type data: GetImagesByKeywordResponseData
        """

        self._data = data

