# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.image import Image
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GetFeedResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, data: List[Image]=None):
        """
        GetFeedResponse - a model defined in Swagger

        :param message: The message of this GetFeedResponse.
        :type message: str
        :param data: The data of this GetFeedResponse.
        :type data: List[Image]
        """
        self.swagger_types = {
            'message': str,
            'data': List[Image]
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetFeedResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetFeedResponse of this GetFeedResponse.
        :rtype: GetFeedResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this GetFeedResponse.

        :return: The message of this GetFeedResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this GetFeedResponse.

        :param message: The message of this GetFeedResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> List[Image]:
        """
        Gets the data of this GetFeedResponse.

        :return: The data of this GetFeedResponse.
        :rtype: List[Image]
        """
        return self._data

    @data.setter
    def data(self, data: List[Image]):
        """
        Sets the data of this GetFeedResponse.

        :param data: The data of this GetFeedResponse.
        :type data: List[Image]
        """

        self._data = data

