# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.image import Image  # noqa: F401,E501
from swagger_server import util


class GetImageResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: Image=None):  # noqa: E501
        """GetImageResponse - a model defined in Swagger

        :param message: The message of this GetImageResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GetImageResponse.  # noqa: E501
        :type data: Image
        """
        self.swagger_types = {
            'message': str,
            'data': Image
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetImageResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetImageResponse of this GetImageResponse.  # noqa: E501
        :rtype: GetImageResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetImageResponse.


        :return: The message of this GetImageResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetImageResponse.


        :param message: The message of this GetImageResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> Image:
        """Gets the data of this GetImageResponse.


        :return: The data of this GetImageResponse.
        :rtype: Image
        """
        return self._data

    @data.setter
    def data(self, data: Image):
        """Sets the data of this GetImageResponse.


        :param data: The data of this GetImageResponse.
        :type data: Image
        """

        self._data = data
