# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_objects_response_data import GetObjectsResponseData  # noqa: F401,E501
from swagger_server import util


class GetObjectsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: GetObjectsResponseData=None):  # noqa: E501
        """GetObjectsResponse - a model defined in Swagger

        :param message: The message of this GetObjectsResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GetObjectsResponse.  # noqa: E501
        :type data: GetObjectsResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': GetObjectsResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetObjectsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetObjectsResponse of this GetObjectsResponse.  # noqa: E501
        :rtype: GetObjectsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetObjectsResponse.


        :return: The message of this GetObjectsResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetObjectsResponse.


        :param message: The message of this GetObjectsResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> GetObjectsResponseData:
        """Gets the data of this GetObjectsResponse.


        :return: The data of this GetObjectsResponse.
        :rtype: GetObjectsResponseData
        """
        return self._data

    @data.setter
    def data(self, data: GetObjectsResponseData):
        """Sets the data of this GetObjectsResponse.


        :param data: The data of this GetObjectsResponse.
        :type data: GetObjectsResponseData
        """

        self._data = data
