# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.boxes_array import BoxesArray
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GetObjectsResponseData(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, boxes: BoxesArray=None):
        """
        GetObjectsResponseData - a model defined in Swagger

        :param boxes: The boxes of this GetObjectsResponseData.
        :type boxes: BoxesArray
        """
        self.swagger_types = {
            'boxes': BoxesArray
        }

        self.attribute_map = {
            'boxes': 'boxes'
        }

        self._boxes = boxes

    @classmethod
    def from_dict(cls, dikt) -> 'GetObjectsResponseData':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetObjectsResponse_data of this GetObjectsResponseData.
        :rtype: GetObjectsResponseData
        """
        return deserialize_model(dikt, cls)

    @property
    def boxes(self) -> BoxesArray:
        """
        Gets the boxes of this GetObjectsResponseData.

        :return: The boxes of this GetObjectsResponseData.
        :rtype: BoxesArray
        """
        return self._boxes

    @boxes.setter
    def boxes(self, boxes: BoxesArray):
        """
        Sets the boxes of this GetObjectsResponseData.

        :param boxes: The boxes of this GetObjectsResponseData.
        :type boxes: BoxesArray
        """

        self._boxes = boxes

