# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.image import Image  # noqa: F401,E501
from swagger_server import util


class GetImagesResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: List[Image]=None):  # noqa: E501
        """GetImagesResponse - a model defined in Swagger

        :param message: The message of this GetImagesResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GetImagesResponse.  # noqa: E501
        :type data: List[Image]
        """
        self.swagger_types = {
            'message': str,
            'data': List[Image]
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetImagesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetImagesResponse of this GetImagesResponse.  # noqa: E501
        :rtype: GetImagesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetImagesResponse.


        :return: The message of this GetImagesResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetImagesResponse.


        :param message: The message of this GetImagesResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> List[Image]:
        """Gets the data of this GetImagesResponse.


        :return: The data of this GetImagesResponse.
        :rtype: List[Image]
        """
        return self._data

    @data.setter
    def data(self, data: List[Image]):
        """Sets the data of this GetImagesResponse.


        :param data: The data of this GetImagesResponse.
        :type data: List[Image]
        """

        self._data = data
