# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Product(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, host_code: str=None, host_url: str=None, host_name: str=None, tags: List[str]=None, class_code: str=None, price: int=None, currency_unit: str=None, product_url: str=None, product_no: str=None, nation: str=None, main_image: str=None, main_image_mobile_full: str=None, main_image_mobile_thumb: str=None, sizes: List[str]=None, discount_rate: int=None, version: str=None):
        """
        Product - a model defined in Swagger

        :param id: The id of this Product.
        :type id: str
        :param name: The name of this Product.
        :type name: str
        :param host_code: The host_code of this Product.
        :type host_code: str
        :param host_url: The host_url of this Product.
        :type host_url: str
        :param host_name: The host_name of this Product.
        :type host_name: str
        :param tags: The tags of this Product.
        :type tags: List[str]
        :param class_code: The class_code of this Product.
        :type class_code: str
        :param price: The price of this Product.
        :type price: int
        :param currency_unit: The currency_unit of this Product.
        :type currency_unit: str
        :param product_url: The product_url of this Product.
        :type product_url: str
        :param product_no: The product_no of this Product.
        :type product_no: str
        :param nation: The nation of this Product.
        :type nation: str
        :param main_image: The main_image of this Product.
        :type main_image: str
        :param main_image_mobile_full: The main_image_mobile_full of this Product.
        :type main_image_mobile_full: str
        :param main_image_mobile_thumb: The main_image_mobile_thumb of this Product.
        :type main_image_mobile_thumb: str
        :param sizes: The sizes of this Product.
        :type sizes: List[str]
        :param discount_rate: The discount_rate of this Product.
        :type discount_rate: int
        :param version: The version of this Product.
        :type version: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'host_code': str,
            'host_url': str,
            'host_name': str,
            'tags': List[str],
            'class_code': str,
            'price': int,
            'currency_unit': str,
            'product_url': str,
            'product_no': str,
            'nation': str,
            'main_image': str,
            'main_image_mobile_full': str,
            'main_image_mobile_thumb': str,
            'sizes': List[str],
            'discount_rate': int,
            'version': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'host_code': 'host_code',
            'host_url': 'host_url',
            'host_name': 'host_name',
            'tags': 'tags',
            'class_code': 'class_code',
            'price': 'price',
            'currency_unit': 'currency_unit',
            'product_url': 'product_url',
            'product_no': 'product_no',
            'nation': 'nation',
            'main_image': 'main_image',
            'main_image_mobile_full': 'main_image_mobile_full',
            'main_image_mobile_thumb': 'main_image_mobile_thumb',
            'sizes': 'sizes',
            'discount_rate': 'discount_rate',
            'version': 'version'
        }

        self._id = id
        self._name = name
        self._host_code = host_code
        self._host_url = host_url
        self._host_name = host_name
        self._tags = tags
        self._class_code = class_code
        self._price = price
        self._currency_unit = currency_unit
        self._product_url = product_url
        self._product_no = product_no
        self._nation = nation
        self._main_image = main_image
        self._main_image_mobile_full = main_image_mobile_full
        self._main_image_mobile_thumb = main_image_mobile_thumb
        self._sizes = sizes
        self._discount_rate = discount_rate
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.
        :rtype: Product
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """
        Gets the id of this Product.

        :return: The id of this Product.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """
        Sets the id of this Product.

        :param id: The id of this Product.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """
        Gets the name of this Product.

        :return: The name of this Product.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Product.

        :param name: The name of this Product.
        :type name: str
        """

        self._name = name

    @property
    def host_code(self) -> str:
        """
        Gets the host_code of this Product.

        :return: The host_code of this Product.
        :rtype: str
        """
        return self._host_code

    @host_code.setter
    def host_code(self, host_code: str):
        """
        Sets the host_code of this Product.

        :param host_code: The host_code of this Product.
        :type host_code: str
        """

        self._host_code = host_code

    @property
    def host_url(self) -> str:
        """
        Gets the host_url of this Product.

        :return: The host_url of this Product.
        :rtype: str
        """
        return self._host_url

    @host_url.setter
    def host_url(self, host_url: str):
        """
        Sets the host_url of this Product.

        :param host_url: The host_url of this Product.
        :type host_url: str
        """

        self._host_url = host_url

    @property
    def host_name(self) -> str:
        """
        Gets the host_name of this Product.

        :return: The host_name of this Product.
        :rtype: str
        """
        return self._host_name

    @host_name.setter
    def host_name(self, host_name: str):
        """
        Sets the host_name of this Product.

        :param host_name: The host_name of this Product.
        :type host_name: str
        """

        self._host_name = host_name

    @property
    def tags(self) -> List[str]:
        """
        Gets the tags of this Product.

        :return: The tags of this Product.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """
        Sets the tags of this Product.

        :param tags: The tags of this Product.
        :type tags: List[str]
        """

        self._tags = tags

    @property
    def class_code(self) -> str:
        """
        Gets the class_code of this Product.

        :return: The class_code of this Product.
        :rtype: str
        """
        return self._class_code

    @class_code.setter
    def class_code(self, class_code: str):
        """
        Sets the class_code of this Product.

        :param class_code: The class_code of this Product.
        :type class_code: str
        """

        self._class_code = class_code

    @property
    def price(self) -> int:
        """
        Gets the price of this Product.

        :return: The price of this Product.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price: int):
        """
        Sets the price of this Product.

        :param price: The price of this Product.
        :type price: int
        """

        self._price = price

    @property
    def currency_unit(self) -> str:
        """
        Gets the currency_unit of this Product.

        :return: The currency_unit of this Product.
        :rtype: str
        """
        return self._currency_unit

    @currency_unit.setter
    def currency_unit(self, currency_unit: str):
        """
        Sets the currency_unit of this Product.

        :param currency_unit: The currency_unit of this Product.
        :type currency_unit: str
        """

        self._currency_unit = currency_unit

    @property
    def product_url(self) -> str:
        """
        Gets the product_url of this Product.

        :return: The product_url of this Product.
        :rtype: str
        """
        return self._product_url

    @product_url.setter
    def product_url(self, product_url: str):
        """
        Sets the product_url of this Product.

        :param product_url: The product_url of this Product.
        :type product_url: str
        """

        self._product_url = product_url

    @property
    def product_no(self) -> str:
        """
        Gets the product_no of this Product.

        :return: The product_no of this Product.
        :rtype: str
        """
        return self._product_no

    @product_no.setter
    def product_no(self, product_no: str):
        """
        Sets the product_no of this Product.

        :param product_no: The product_no of this Product.
        :type product_no: str
        """

        self._product_no = product_no

    @property
    def nation(self) -> str:
        """
        Gets the nation of this Product.

        :return: The nation of this Product.
        :rtype: str
        """
        return self._nation

    @nation.setter
    def nation(self, nation: str):
        """
        Sets the nation of this Product.

        :param nation: The nation of this Product.
        :type nation: str
        """

        self._nation = nation

    @property
    def main_image(self) -> str:
        """
        Gets the main_image of this Product.
        image url

        :return: The main_image of this Product.
        :rtype: str
        """
        return self._main_image

    @main_image.setter
    def main_image(self, main_image: str):
        """
        Sets the main_image of this Product.
        image url

        :param main_image: The main_image of this Product.
        :type main_image: str
        """

        self._main_image = main_image

    @property
    def main_image_mobile_full(self) -> str:
        """
        Gets the main_image_mobile_full of this Product.
        Mobile full size of image url

        :return: The main_image_mobile_full of this Product.
        :rtype: str
        """
        return self._main_image_mobile_full

    @main_image_mobile_full.setter
    def main_image_mobile_full(self, main_image_mobile_full: str):
        """
        Sets the main_image_mobile_full of this Product.
        Mobile full size of image url

        :param main_image_mobile_full: The main_image_mobile_full of this Product.
        :type main_image_mobile_full: str
        """

        self._main_image_mobile_full = main_image_mobile_full

    @property
    def main_image_mobile_thumb(self) -> str:
        """
        Gets the main_image_mobile_thumb of this Product.
        Mobile thumbnail size of image url

        :return: The main_image_mobile_thumb of this Product.
        :rtype: str
        """
        return self._main_image_mobile_thumb

    @main_image_mobile_thumb.setter
    def main_image_mobile_thumb(self, main_image_mobile_thumb: str):
        """
        Sets the main_image_mobile_thumb of this Product.
        Mobile thumbnail size of image url

        :param main_image_mobile_thumb: The main_image_mobile_thumb of this Product.
        :type main_image_mobile_thumb: str
        """

        self._main_image_mobile_thumb = main_image_mobile_thumb

    @property
    def sizes(self) -> List[str]:
        """
        Gets the sizes of this Product.

        :return: The sizes of this Product.
        :rtype: List[str]
        """
        return self._sizes

    @sizes.setter
    def sizes(self, sizes: List[str]):
        """
        Sets the sizes of this Product.

        :param sizes: The sizes of this Product.
        :type sizes: List[str]
        """

        self._sizes = sizes

    @property
    def discount_rate(self) -> int:
        """
        Gets the discount_rate of this Product.

        :return: The discount_rate of this Product.
        :rtype: int
        """
        return self._discount_rate

    @discount_rate.setter
    def discount_rate(self, discount_rate: int):
        """
        Sets the discount_rate of this Product.

        :param discount_rate: The discount_rate of this Product.
        :type discount_rate: int
        """

        self._discount_rate = discount_rate

    @property
    def version(self) -> str:
        """
        Gets the version of this Product.

        :return: The version of this Product.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """
        Sets the version of this Product.

        :param version: The version of this Product.
        :type version: str
        """

        self._version = version

