# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class SimImage(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: str=None, product_name: str=None, product_id: str=None, host_code: str=None, host_url: str=None, host_name: str=None, class_code: str=None, price: int=None, currency_unit: str=None, product_url: str=None, product_no: str=None, nation: str=None, main_image_mobile_full: str=None, main_image_mobile_thumb: str=None, version: str=None):
        """
        SimImage - a model defined in Swagger

        :param id: The id of this SimImage.
        :type id: str
        :param product_name: The product_name of this SimImage.
        :type product_name: str
        :param product_id: The product_id of this SimImage.
        :type product_id: str
        :param host_code: The host_code of this SimImage.
        :type host_code: str
        :param host_url: The host_url of this SimImage.
        :type host_url: str
        :param host_name: The host_name of this SimImage.
        :type host_name: str
        :param class_code: The class_code of this SimImage.
        :type class_code: str
        :param price: The price of this SimImage.
        :type price: int
        :param currency_unit: The currency_unit of this SimImage.
        :type currency_unit: str
        :param product_url: The product_url of this SimImage.
        :type product_url: str
        :param product_no: The product_no of this SimImage.
        :type product_no: str
        :param nation: The nation of this SimImage.
        :type nation: str
        :param main_image_mobile_full: The main_image_mobile_full of this SimImage.
        :type main_image_mobile_full: str
        :param main_image_mobile_thumb: The main_image_mobile_thumb of this SimImage.
        :type main_image_mobile_thumb: str
        :param version: The version of this SimImage.
        :type version: str
        """
        self.swagger_types = {
            'id': str,
            'product_name': str,
            'product_id': str,
            'host_code': str,
            'host_url': str,
            'host_name': str,
            'class_code': str,
            'price': int,
            'currency_unit': str,
            'product_url': str,
            'product_no': str,
            'nation': str,
            'main_image_mobile_full': str,
            'main_image_mobile_thumb': str,
            'version': str
        }

        self.attribute_map = {
            'id': 'id',
            'product_name': 'product_name',
            'product_id': 'product_id',
            'host_code': 'host_code',
            'host_url': 'host_url',
            'host_name': 'host_name',
            'class_code': 'class_code',
            'price': 'price',
            'currency_unit': 'currency_unit',
            'product_url': 'product_url',
            'product_no': 'product_no',
            'nation': 'nation',
            'main_image_mobile_full': 'main_image_mobile_full',
            'main_image_mobile_thumb': 'main_image_mobile_thumb',
            'version': 'version'
        }

        self._id = id
        self._product_name = product_name
        self._product_id = product_id
        self._host_code = host_code
        self._host_url = host_url
        self._host_name = host_name
        self._class_code = class_code
        self._price = price
        self._currency_unit = currency_unit
        self._product_url = product_url
        self._product_no = product_no
        self._nation = nation
        self._main_image_mobile_full = main_image_mobile_full
        self._main_image_mobile_thumb = main_image_mobile_thumb
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'SimImage':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SimImage of this SimImage.
        :rtype: SimImage
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """
        Gets the id of this SimImage.

        :return: The id of this SimImage.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """
        Sets the id of this SimImage.

        :param id: The id of this SimImage.
        :type id: str
        """

        self._id = id

    @property
    def product_name(self) -> str:
        """
        Gets the product_name of this SimImage.

        :return: The product_name of this SimImage.
        :rtype: str
        """
        return self._product_name

    @product_name.setter
    def product_name(self, product_name: str):
        """
        Sets the product_name of this SimImage.

        :param product_name: The product_name of this SimImage.
        :type product_name: str
        """

        self._product_name = product_name

    @property
    def product_id(self) -> str:
        """
        Gets the product_id of this SimImage.

        :return: The product_id of this SimImage.
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: str):
        """
        Sets the product_id of this SimImage.

        :param product_id: The product_id of this SimImage.
        :type product_id: str
        """

        self._product_id = product_id

    @property
    def host_code(self) -> str:
        """
        Gets the host_code of this SimImage.

        :return: The host_code of this SimImage.
        :rtype: str
        """
        return self._host_code

    @host_code.setter
    def host_code(self, host_code: str):
        """
        Sets the host_code of this SimImage.

        :param host_code: The host_code of this SimImage.
        :type host_code: str
        """

        self._host_code = host_code

    @property
    def host_url(self) -> str:
        """
        Gets the host_url of this SimImage.

        :return: The host_url of this SimImage.
        :rtype: str
        """
        return self._host_url

    @host_url.setter
    def host_url(self, host_url: str):
        """
        Sets the host_url of this SimImage.

        :param host_url: The host_url of this SimImage.
        :type host_url: str
        """

        self._host_url = host_url

    @property
    def host_name(self) -> str:
        """
        Gets the host_name of this SimImage.

        :return: The host_name of this SimImage.
        :rtype: str
        """
        return self._host_name

    @host_name.setter
    def host_name(self, host_name: str):
        """
        Sets the host_name of this SimImage.

        :param host_name: The host_name of this SimImage.
        :type host_name: str
        """

        self._host_name = host_name

    @property
    def class_code(self) -> str:
        """
        Gets the class_code of this SimImage.

        :return: The class_code of this SimImage.
        :rtype: str
        """
        return self._class_code

    @class_code.setter
    def class_code(self, class_code: str):
        """
        Sets the class_code of this SimImage.

        :param class_code: The class_code of this SimImage.
        :type class_code: str
        """

        self._class_code = class_code

    @property
    def price(self) -> int:
        """
        Gets the price of this SimImage.

        :return: The price of this SimImage.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price: int):
        """
        Sets the price of this SimImage.

        :param price: The price of this SimImage.
        :type price: int
        """

        self._price = price

    @property
    def currency_unit(self) -> str:
        """
        Gets the currency_unit of this SimImage.

        :return: The currency_unit of this SimImage.
        :rtype: str
        """
        return self._currency_unit

    @currency_unit.setter
    def currency_unit(self, currency_unit: str):
        """
        Sets the currency_unit of this SimImage.

        :param currency_unit: The currency_unit of this SimImage.
        :type currency_unit: str
        """

        self._currency_unit = currency_unit

    @property
    def product_url(self) -> str:
        """
        Gets the product_url of this SimImage.

        :return: The product_url of this SimImage.
        :rtype: str
        """
        return self._product_url

    @product_url.setter
    def product_url(self, product_url: str):
        """
        Sets the product_url of this SimImage.

        :param product_url: The product_url of this SimImage.
        :type product_url: str
        """

        self._product_url = product_url

    @property
    def product_no(self) -> str:
        """
        Gets the product_no of this SimImage.

        :return: The product_no of this SimImage.
        :rtype: str
        """
        return self._product_no

    @product_no.setter
    def product_no(self, product_no: str):
        """
        Sets the product_no of this SimImage.

        :param product_no: The product_no of this SimImage.
        :type product_no: str
        """

        self._product_no = product_no

    @property
    def nation(self) -> str:
        """
        Gets the nation of this SimImage.

        :return: The nation of this SimImage.
        :rtype: str
        """
        return self._nation

    @nation.setter
    def nation(self, nation: str):
        """
        Sets the nation of this SimImage.

        :param nation: The nation of this SimImage.
        :type nation: str
        """

        self._nation = nation

    @property
    def main_image_mobile_full(self) -> str:
        """
        Gets the main_image_mobile_full of this SimImage.
        Mobile full size of image url

        :return: The main_image_mobile_full of this SimImage.
        :rtype: str
        """
        return self._main_image_mobile_full

    @main_image_mobile_full.setter
    def main_image_mobile_full(self, main_image_mobile_full: str):
        """
        Sets the main_image_mobile_full of this SimImage.
        Mobile full size of image url

        :param main_image_mobile_full: The main_image_mobile_full of this SimImage.
        :type main_image_mobile_full: str
        """

        self._main_image_mobile_full = main_image_mobile_full

    @property
    def main_image_mobile_thumb(self) -> str:
        """
        Gets the main_image_mobile_thumb of this SimImage.
        Mobile thumbnail size of image url

        :return: The main_image_mobile_thumb of this SimImage.
        :rtype: str
        """
        return self._main_image_mobile_thumb

    @main_image_mobile_thumb.setter
    def main_image_mobile_thumb(self, main_image_mobile_thumb: str):
        """
        Sets the main_image_mobile_thumb of this SimImage.
        Mobile thumbnail size of image url

        :param main_image_mobile_thumb: The main_image_mobile_thumb of this SimImage.
        :type main_image_mobile_thumb: str
        """

        self._main_image_mobile_thumb = main_image_mobile_thumb

    @property
    def version(self) -> str:
        """
        Gets the version of this SimImage.

        :return: The version of this SimImage.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """
        Sets the version of this SimImage.

        :param version: The version of this SimImage.
        :type version: str
        """

        self._version = version

